name: Create pull request
on:
  push:
    branches:
      - gh-pages-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages-build
        base: master
